### ISSUE TITLE
How to save the mask?

### ISSUE THREAD

**Issue by dani-lbnl** [LauLauThom/MaskFromRois-Fiji#5]
Current instructions are not enough - can you please indicate how to save the mask for the multiclass case? which part of the several menus within fiji? thx

**Comment by LauLauThom** [comment]
The masks are usual ImageJ images which can be saved under `File > Save As`. I advise using tiff to make sure the values are not modified by some compression or so.
When opening the image, select an adapted Look Up Table (Image > Lookup Tables > Glasbey for instance), otherwise it might appear that the image is black
